version: 0.2

phases:
  install:
    commands:
      - echo installing Maven...
      - apt-get update -y
      - apt-get install -y maven
      - echo installing JDK 17...
      - apt-get install -y openjdk-17-jdk-headless
      - echo $JAVA_HOME
      - java -version
      - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - chmod +x $HOME/.nvm/nvm.sh
      - $HOME/.nvm/nvm.sh install v16.13.1
      - npm install -g @angular/cli@13.1.1
      - apt-get install -y git
  build:
    commands:
      - echo Build started on `date`
      - mvn verify -f ./med-assist-backend/pom.xml  -DskipTests -Dmaven.gitcommitid.skip=true
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Building frontend
      - cd ./med-assist-frontend/ && npm install --silent && ng build --aot --outputHashing=all --configuration=production && cd ..
      - cd ./med-assist-frontend/dist/ && tar -cf fe.tar med-assist-client && cd ../../
      - mv ./med-assist-backend/target/med-assist-backend-0.0.1-SNAPSHOT.jar ./med-assist-backend/target/med-assist.jar
artifacts:
  files:
      - ./med-assist-backend/target/med-assist.jar
      - ./med-assist-frontend/dist/fe.tar
      - ./appspec.yml
      - ./med-assist-backend/infrastructure/deployment/before-install.sh
      - ./med-assist-backend/infrastructure/deployment/after-install.sh
      - ./med-assist-backend/infrastructure/deployment/start.sh
      - ./med-assist-backend/infrastructure/deployment/check-health.sh
  discard-paths: yes
