###Create doctor
POST http://localhost:8080/api/v1/doctors
Content-Type: application/json

{
  "name": "Jim",
  "speciality": "ORTHODONTIST"
}

###

### Send POST request with json body
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "square-pants",
  "email" : "sponge-bob@gmail.com",
  "firstName" : "Sponge",
  "lastName" : "Bob",
  "password": "123456",
  "authorities" : ["POWER_USER"]
}


### Send POST request with json body
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "square-pants",
  "password": "123456"
}

### All users
GET http://localhost:8080/api/v1/users/
Content-Type: application/json
Authorization: {{authKey}}


### User by id
GET http://localhost:8080/api/v1/users/7afdf291-cd73-4055-b2e4-ada5bc21bfca
Content-Type: application/json
Authorization: {{authKey}}

### Send PUT request with json body
PUT http://localhost:8080/api/v1/users/7afdf291-cd73-4055-b2e4-ada5bc21bfca
Content-Type: application/json
Authorization: {{authKey}}

{
  "email" : "bdylan@rocknrollcafe.com"
}

###
GET http://localhost:8080/api/v1/doctors
Authorization: {{authKey}}

###
GET http://localhost:8080/api/v1/patients
Authorization: {{authKey}}

### Send POST request with json body
POST http://localhost:8080/api/v1/patients
Content-Type: application/json
Authorization: {{authKey}}

{

  "firstName" : "Vasile",
  "lastName" : "Usaci",
  "phoneNumber": "37369666666",
  "birthDate": "1995-11-15"
}


### Send POST request with json body
POST http://localhost:8080/api/v1/doctors
Content-Type: application/json
Authorization: {{authKey}}

{
  "username": "vusaci",
  "email" : "vusaci@gmail.com",
  "firstName" : "Vasile",
  "lastName" : "Usaci",
  "password": "123456",
  "telephoneNumber": "37369666666",
  "specialty": "ORTHODONTIST",
  "authorities" : ["DOCTOR"]
}

### Send POST request with json body
POST http://localhost:8080/api/v1/appointments
Content-Type: application/json
Authorization: {{authKey}}

{
  "patientId": "505eeca9-cb8f-4420-bf28-1bc7b313acbb",
  "doctorId": "aa80a68a-7a6f-43be-a88b-e88cc467cbf6",
  "appointmentDate" : "2021-12-15",
  "startTime" : "17:00:00",
  "endTime" : "18:00:00",
  "operation": "Cleaning",
  "details": "New patient"
}

###
GET http://localhost:8080/api/v1/appointments
Authorization: {{authKey}}
